name: Terraform Destroy Azure Resources

on:
  schedule:
    - cron: '30 9 * * *'  # UTC 09:30 (KST 18:30)
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_admin_password: ${{ secrets.VM_ADMIN_PASSWORD }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: List files
      run: |
        ls -la
        pwd

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.7

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="storage_account_name=lswterraformstate0621" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="resource_group_name=peterlah-rg"

    - name: Terraform Plan Destroy
      run: terraform plan -destroy

    - name: Terraform Destroy
      run: terraform destroy -auto-approve